theme: jekyll-theme-leap-day
title: Micronaut Serialization for Result
description: Serialize and deserialize Result objects with Micronaut
current_version: 1.0.0.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-micronaut-serde
